### ISSUE TITLE
Short station names not updating

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_SI4713#9]
In example below, just change `station` to something with less than 8 characters.

```python
import board, digitalio, adafruit_si4713
si_reset = digitalio.DigitalInOut(board.D10)
si4713 = adafruit_si4713.SI4713(board.I2C(), reset=si_reset, timeout_s=0.5)
si4713.tx_frequency_khz = 87500
si4713.tx_power = 115
si4713.configure_rds(0xADAF, station=b'12345678', rds_buffer=b'solid gold yacht rock')
```

**Comment by jposada202020** [comment]
Helllo @caternuson I ytested this but could not repeat the issue.

```python
Adafruit CircuitPython 6.2.0 on 2021-04-05; Adafruit Feather RP2040 with rp2040
>>> import board
>>> import digitalio
>>> import adafruit_si4713
>>> si_reset = digitalio.DigitalInOut(board.D5)
>>> si4713 = adafruit_si4713.SI4713(board.I2C(), reset=si_reset, timeout_s=0.5)
>>> si4713.tx_frequency_khz = 87500
>>> si4713.tx_power = 115
>>> si4713.configure_rds(0xADAF, station=b'ocho', rds_buffer=b'solid gold yacht rock')
>>>
```

**Comment by caternuson** [comment]
@jposada202020 What are you using for receiving the RDS info?

**Comment by jposada202020** [comment]
@caternuson mmmm, Not using not a receiver. Was trying to see where the issue was. So the only thing that I did was change the station.
If I need to do something let me know I would like to work in this issue 😃

**Comment by caternuson** [comment]
I'm trying to remember some of these details myself :smiley: 
I *think* the issue was on the receiving end. The code would run without errors, but you wouldn't see the updated name on the receiving radio. I'm pretty sure I was using a Zune (yes, a Zune) to test things on the receiving end.

**Comment by jposada202020** [comment]
Oh dear.... Gotcha.. lets see what I can do :)

**Comment by jposada202020** [comment]
@caternuson 
Ok.. :) .. now the real issue is, when using less than five characters, the station will add `bs` to the name
![image](https://user-images.githubusercontent.com/34255413/120839928-92b2da00-c537-11eb-8b6d-010494fd016d.png)

I will try to troubleshoot this during the weekend now that I have how to test.

according to initial testing I am guessing that the buffer is not being cleared, but I have not even study a single line of code of the library.. :)

**Comment by caternuson** [comment]
@jposada202020 cool. it looks like you generally are recreating the issue. i also did not dig into this very far. seemed like a weird edge case and at the time needed to move on to other things. so just created this issue as a reminder, or for anyone else that might wander into it :) thanks!
